- django_celery_results/migrations/0001_initial.py
> Make initial migration

- t/proj/celery.py
- t/proj/settings.py
- t/proj/wsgi.py
Fix django and celery settings with correct path to project, some settings, etc.
> Fix django and celery test project settings

- Changelog
- README.rst
@ask I have updated the Changelog file as well as README for the newer release.
> Updated the Changelog and README for newer version

- django_celery_results/managers.py
This should fix the issue mentioned in #83 by using the correct system variable depending on the version of MySQL being used.
> Fix MySQL8 system variable issue

- django_celery_results/managers.py
Fixes again #83, since #84 introduced a regression in MariaDB, which as of 10.3 still uses the old `tx_isolation` name.
> Fix transaction_isolation regression in MariaDB

- django_celery_results/admin.py
> Admin site - add worker to list_filter

- django_celery_results/migrations/0006_taskresult_date_created.py
> Make 0006 migration reversible (fixes #132)

- README.rst
I'm sorry but I don't think I can push to someone else's PR, so I just wanted to try and merge this README fix proposed in #138 with the updates introduced in #163 to see if it solves the tests issue (I'm getting strange exceptions that are not raised in Travis, so I can't check locally). If this passes it closes #138.
> README link fix

- t/unit/backends/test_database.py
> Fix some test_DatabaseBackend tests

- django_celery_results/backends/database.py
- t/unit/backends/test_database.py
> Match `apply_chord` call signature to Celery 5.1

- django_celery_results/urls.py
> 212 typo fix

- django_celery_results/views.py
- t/unit/test_views.py
closes #214 
api view will return json of this format
```json
{
"group": {
"id": "ID_HERE",
"results": [
{"result": "result here or null", "status": "STATUS"}
]
}
}
```
> fix group status view return data, add tests for it

- django_celery_results/urls.py
> add new urls with nouns first structure

- locale/ru/LC_MESSAGES/django.po
Translation updates after code review in #255
> Russian translation updates

- locale/ru/LC_MESSAGES/django.po
- locale/zh_Hans/LC_MESSAGES/django.po
As a Chinese user, I noticed that there is no Simplified Chinese translation, so I added one by myself. And then fix a comment typo btw. Hope to be merged.
> Add Simplified Chinese translation strings and fix comment typo.

- AUTHORS
- django_celery_results/locale/pt_BR/LC_MESSAGES/django.po
This only add translation messages to brazilian portuguese.
> Add translation of the messages to brazilian portuguese

- django_celery_results/backends/database.py
suggested fix for https://github.com/celery/django-celery-results/issues/308
> try  possible fix to avoid a oracle regression

- django_celery_results/admin.py
> Added `periodic_task_name` to admin fieldset for parity with list view

- requirements/test.txt
> Remove ">dev" from pytz dependency specifier

- .editorconfig
- LICENSE
- README.rst
- docs/Makefile
- docs/conf.py
- docs/copyright.rst
- docs/includes/installation.txt
- docs/includes/introduction.txt
- docs/make.bat
- docs/templates/readme.txt
- setup.py
Also updated a few links that were pointing to redirects.
> Convert insecure links to use HTTPS
