- django_celery_results/backends/database.py
The original functions (from `base64`) return `bytes` objects on Python 3. Django 2 does not encode them to `str` before putting them in the database, resulting in strings like `"b'gAJ9cQBYCAAAAGNoaWxkcmVucQFdcQJzLg=='"` ending up in the database. Those in turn cannot be correctly `b64decode`-d and unpickled.
Using `celery`'s wrapper functions solves that problem.
> Use celery's b64decode and b64encode

- django_celery_results/admin.py
Since this is primarily for viewing results, in our use case I don't really find it makes sense to allow people to edit the fields in the admin.
At best it will be confusing for regular users, I would like to encourage them to use this UI to provide more detail when reporting on one of their scheduled Beat tasks that has failed but don't want them to edit things.
I suppose some people might be using it as a testing tool or reprocessing results they edit the status of somehow though, so this adds a `DJANGO_CELERY_RESULTS` Django setting, with an `ALLOW_EDITS` key that can be set.
So you can add:
```python
DJANGO_CELERY_RESULTS: {
'ALLOW_EDITS': False
}
```
to your Django config and it will make all fields read-only.
Default behaviour is unchanged.
> Add ALLOW_EDITS Django setting

- django_celery_results/admin.py
- django_celery_results/models.py
Some minor tweaks to the list view that make life easier when there are results that tend to be clustered together in large quantities:
- Default ordering to date descending
- Have the first field / linked field in the list be the Task ID (when you click you are clicking to view that task, not anything about the task name, which is often repeated hundreds of times in a row)
> Admin list

- django_celery_results/admin.py
Some convenience additions to the list view to allow people to more easily skim through large result sets:
- Date hierarchy for browsing by date more easily over a longer period of time
- Filter by task name (eg. to see results of a daily task amongst a large list of those run every minute)
- Search by task details (eg. to find the results of a single item you know ran, or to search all "category.taskname failure" without clicking multiple filters)
> Admin filters

- django_celery_results/managers.py
To resolve issue #79 using the delete() method of a queryset.
All unit tests are passed. Please review if there is any side effect.
> use queryset's deletion method instead

- django_celery_results/backends/database.py
- t/unit/backends/test_database.py
Current version ignores argsrepr and kwargsrepr so sensitive information is saved in the database...this change fixes that:
Refer to
http://docs.celeryproject.org/en/latest/userguide/tasks.html#hiding-sensitive-information-in-arguments
for more information on hiding sensitive information.
> Add support for hiding sensitive information with celery argsrepr and kwargsrepr

- django_celery_results/migrations/0004_auto_20190516_0412.py
Fix 0004 migration, use `DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH` setting in the `task_id.max_length` instead of hardcoding `191` value.
> Fix 0004 migration

- tox.ini
It seems Django 2.1 wasn't properly tested on Travis due to a copy paste error.
> Fix tox file for Django 2.1

- django_celery_results/managers.py
The origin query would have the following error when querying mysql5.6.
```
Unknown column 'tx_isolation' in 'where clause'
```
> change double quotes to single quotes for support mysql5.6 query

- README.rst
@auvipy as requested, here is the README marketing text
> Adding the Tidelift marketing text

- django_celery_results/urls.py
- django_celery_results/views.py
- t/unit/test_views.py
This adds the task status API from `django-celery` into the new module (resolves #103 ). Much of the code is copy-paste from the old library, but some changes were necessary for compatibility with newer versions Celery et al. For that reason it was easier to write new tests than adapt the old ones, but of course if that's not OK I can do it the other way.
In my local environment, all tests pass except for `apicheck`, which fails for me because my environment still defaults to python2.7, but `sphinx-celery` requires a version of `sphinx` that only supports python3.5 or greater. 
If I've missed anything or need to clean anything up I'll be happy to!
> add task status api from django-celery

- django_celery_results/admin.py
Django-Celery-Results is meant for monitoring. There is little to no reason to allow editing task results. So it would be better to allow edits only if a user explicitly specifies this setting. This is how it worked in django-celery.
Previous PR: https://github.com/celery/django-celery-results/pull/56
> Make TaskResults read-only by default

- django_celery_results/managers.py
In PR #110 some double quotes were overlooked, resulting in an invalid query.
> Fix bug in warn_if_repeatable_read (introduced in PR #110).

- django_celery_results/admin.py
- django_celery_results/apps.py
- django_celery_results/models.py
Change  ugettext_lazy to gettext_lazy to follows Django recommendations:
```
RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
```
> Change ugettext_lazy to gettext_lazy to remove deprecation Warning

- django_celery_results/backends/database.py
- t/unit/backends/test_database.py
Encode `task_args` and `task_kwargs` in `DatabaseBackend.store_result()` (as we do with `meta` and `result`) so we can retrieve them as python objects later on.
Note that this PR changes the serialization format of these fields.
For example, if `args=['a', 1, True, None]`
Currently it's stored as :
`"['a', 1, True, None]"`
and after this PR it will be stored as:
`'["a", 1, true, null]'` (json format)
> Encode 'task_args' and 'task_kwargs' in 'store_result'.

- django_celery_results/backends/database.py
- t/unit/backends/test_database.py
There is no new feature or behaviour change, just regression and bug fixes, and a lot more testing.
5 commits:
1) First of all I've added a commit so the tests use real task requests instead of MagicMocks, so they are more reliable.
2) Encode original input arguments is not possible in task_protocol=2 (as we already discussed in #113 ), but we didn't realize it because of the use of MagicMock. With the changes of the first commit, tests related with encoding input arguments started to fail (as expected). I've fixed these tests.
3) PR #91 made that `None` was stored to `task_args` and `task_kwargs` instead of the actual input arguments if `task_protocol=1`. I've fixed it, so input arguments are now stored in json format (as expected since #78 ).
4) `AsyncResult` class has `args` and …
> Many bug fixes related with DatabaseBackend._store_result function

- django_celery_results/admin.py
Adding `task_args` and `task_kwargs` to searchable fields in the admin. This is particularly useful in case the arguments provided are specific ids of objects or unique fields.
> Add task_args and task_kwargs to searchable fields

- django_celery_results/backends/database.py
- t/unit/backends/test_database.py
When upgrading from <2.0.0 while current chords are not finished, the ChordCounter object does not exist, breaking the chord.
The `celery.chord_unlock` Task created by the legacy chord should unlock any existing chord while new chord will create the proper ChordCounter object
closes #177
> Don't raise an error when ChordCounter is not found

- django_celery_results/backends/database.py
This will get the Signature["chord_size"] with a fall back to the length of the header when chord_size is not available.
This should correct the chord_size for nested groups in chords
closes #194
> Use the provided chord_size when available

- .github/workflows/test.yaml
- t/proj/settings.py
Run the unittests in GitHub Actions.
This is a possible replacement for the current TravisCI setup.
The unittests rely on a Postgres Docker service so `HOST` and `PASSWORD` had to be added to `settings.py`.
As I'm not familiar with the release process I'm not 100% sure this does not impact releasing.
I'm also not sure how coverage is setup currently so that would have to be added by one of the maintainers.
> Add GitHub workflow for unittesting

- django_celery_results/backends/database.py
With #161 there is a db model introduced named `GroupResult`
This clashed with the `celery.result.GroupResult`
This fixes the name clash in `backends.database`
> Fix "AttributeError: 'AsyncResult' object has no attribute '__len__'"

- django_celery_results/backends/database.py
- t/unit/backends/test_database.py
- t/unit/test_views.py
Store the entire group as serialised by `as_tuple()` instead of the list of Task id's.
This will also change the return value for `_restore_group()["result"]` from `List[AsyncResult]` to `GroupResult` ensuring 
```python
group = GroupResult(group_id)
group.save()
group == <backend>.restore_group(group_id=group_id)
```
> store GroupResult as_tuple()

- django_celery_results/migrations/0009_groupresult.py
- django_celery_results/migrations/0010_remove_duplicate_indices.py
- django_celery_results/models.py
There were explicit indexes added while also defining `unique=True` for the `task_id` and `group_id` fields on all models
This caused two indexes to be created by Django, one for the unique index and one for the explicit index.
Oracle rejects the migration due to duplicated indexes on the same column while Postgres is happy to accept inefficient indexing.
closes #208
> Remove duplicate indexes

- locale/ru/LC_MESSAGES/django.po
> Russian language support

- django_celery_results/backends/database.py
- t/unit/backends/test_database.py
As I can see the value of `properties` should always be a dictionary. For this reason we don't need to handle any falsy values just set it as an empty dictionary if it does not have a valid value.
Fixes #280
> Fix properties default value

- django_celery_results/migrations/0004_auto_20190516_0412.py
- django_celery_results/migrations/0009_groupresult.py
- django_celery_results/models.py
MySQL/MariaDB do not accept indexed fields larger than 191 chars when using `utf8mb4` charset. This makes migrations fail because the `task_name` field is 255-chars long and indexed.
This issue was fixed for the `task_id` field using a new `DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH` Django setting. This PR applies the same fix for field `task_name`.
> Fix field size for MySQL (#285)

- django_celery_results/backends/database.py
- t/unit/test_models.py
This PR implements https://github.com/celery/django-celery-results/issues/119 in a slightly different way. It adds retry logic only for django.db.utils.InterfaceError and psycopg2.InterfaceError, which can be errors like "connection already closed".
It does not retry any DatabaseError, which can be errors like "numeric value out of range" or "foreign key check failed". See https://www.psycopg.org/docs/module.html#exceptions for more info.
exception_safe_to_retry() is overridden from the parent class: https://docs.celeryproject.org/en/stable/_modules/celery/backends/base.html#BaseBackend
This method is called when an exception is raised in _store_result() and always_retry / result_backend_always_retry is set to True. If the exception is an InterfaceError, the connection is closed as a side …
> Add retry logic for Django and Psycopg2 InterfaceErrors

- django_celery_results/backends/database.py
One would reasonably expect django-celery-results to work with other databases without installing psycopg2.
The hard dependency was added in PR #290, probably unintentional without fully understanding this aspect.
> Remove hard dependency on psycopg2

- AUTHORS
- django_celery_results/locale/zh_Hans/LC_MESSAGES/django.po
Add Simplified Chinese missing translations for group related messages.
> Update group related Simplified Chinese translations.

- setup.py
The long description content type is currently set to markdown so the readme isn't displaying correctly; 
https://pypi.org/project/django-celery-results/
This updates it to RST to match the readme file format.
> fix: The description content type set to RST

- .pre-commit-config.yaml
- Changelog
- django_celery_results/backends/database.py
- t/unit/backends/test_database.py
Fixes https://github.com/celery/django-celery-results/issues/315
Currently `django-celery-results` stores all the info about the task to DB whereas the default behavior as per celery should only be storing some basic properties. Extended properties should be saved only when they are requested for. It can be done by setting `extended-result` flag in the celery config.
The PR checks for that flag while storing the results and proceeds accordingly.
I would be adding some tests for it once we are okay with the approach.
> save extended properties only when asked for

- .readthedocs.yaml
- Changelog
- django_celery_results/managers.py
- django_celery_results/models.py
- docs/copyright.rst
- docs/getting_started.rst
- docs/includes/introduction.txt
- requirements/docs.txt
- setup.cfg
This PR is similar to https://github.com/celery/django-celery-beat/pull/527: failing doc build is healed so the documentation hosted under https://django-celery-results.readthedocs.io/en/latest/ should update now. Also fixed Sphinx errors and (most) warnings.
Built result: [django-celery-results-pr docs](https://django-celery-results-pr.readthedocs.io/en/latest/).
> fix documentation build failure, fix sphinx errors and amend sphinx warnings

- django_celery_results/backends/database.py
With the current implementation the following SQL query will be continually executed on every task:
```sql
UPDATE "django_celery_results_chordcounter" 
SET "group_id" = 'f81ac317-eb61-42a6-a750-7cc1feb78b8c', 
"sub_tasks" = '[[["6a2f07d8-6b6f-4286-9d71-dbead46e9b1c", null], null], ..', 
"count" = 122 
WHERE "django_celery_results_chordcounter"."id" = 118
```
If you are using a large number of sub-tasks, ranging in the thousands or tens of thousands, then continually sending the `sub_tasks` in every update can be very expensive.
If we use `update_fields` then we can skip this.
> Only update the ChordCounter.count field when saving

- .github/workflows/test.yaml
We renamed the master branch to main.
We need to adjust the CI workflow.
This PR does just that.
> Update CI to refer to main

- docs/getting_started.rst
Explicitly reference the `track_started` setting to highlight the fact that task execution duration can not be obtained from a task result's `date_created` and `date_done` without a configuration change.
> Document `track_started` setting

- setup.py
These links will be visible on the package's PyPI page, [example](https://pypi.org/project/sentry-sdk/):
> ![image](https://user-images.githubusercontent.com/137616/228550059-2466757b-6edf-43b5-a5f1-0b49690e1b66.png)
Additionally, tools like Renovate bot use these links to provide quicker access to the changelog for a dependency update, and can call GitHub API for additional metadata. Specifically it recognizes `Changelog` and `Repository`.
> Add additional project URLs to PyPI metadata (docs, changelog, repo)

- django_celery_results/backends/database.py
- t/proj/settings.py
- t/unit/backends/test_database.py
Hi,
when using chord with Database result backend and multiple databases with a Database Router we encounter this error:
`select_for_update cannot be used outside of a transaction.`
This depends on the fact that in DatabaseBackend.on_chord_part_return a transaction.atomic is created on the default database and not on the one associated with ChordCounter.
We write this simple fix for handle also this case.
Setting we configured:
```
DATABASES = {
"default": {
"ENGINE": "django.db.backends.postgresql",
"NAME": "data",
},
"celery_result": {
"ENGINE": "django.db.backends.postgresql",
"NAME": "results",
},
}
DATABASE_ROUTERS = [
"app.db_routers.DjangoCeleryResultRouter",
]
```
Router class:
```
class DjangoCeleryResultRouter:
route_app_labels = {"django_celery_results"}
def db_for_read(self, …
```
> Fix atomic transaction not routing to the the correct DB in DatabaseBackend.on_chord_part_return transaction.atomic

- django_celery_results/migrations/0010_remove_duplicate_indices.py
I have been experiencing the following issue, when using django-celery-results with SQLite:
```
Applying django_celery_results.0008_chordcounter... OK
Applying django_celery_results.0009_groupresult... OK
Applying django_celery_results.0010_remove_duplicate_indices...Traceback (most recent call last):
File "/opt/ldr/app/./manage.py", line 26, in <module>
main()
File "/opt/ldr/app/./manage.py", line 22, in main
execute_from_command_line(sys.argv)
File "/opt/ldr/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
utility.execute()
File "/opt/ldr/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File …
```
> Added extra except clause to TryRemoveIndex

- django_celery_results/backends/database.py
[Celery documentation](https://docs.celeryq.dev/en/stable/userguide/configuration.html#std-setting-result_expires) indicates that app.result_expires (or CELERY_RESULT_EXPIRES) should respect values of 0 or None: "A value of None or 0 means results will never expire (depending on backend specifications)."
> update behavior of app.result_expires to match celery docs

- requirements/test.txt
- t/conftest.py
Extracted from #458 
Copy required pytest fixtures from Celery https://github.com/celery/celery/pull/7077
Tried to use the `patching` fixture directly from Celery in https://github.com/celery/django-celery-results/pull/461 but that doesn't work.
> Remove case dependency and copy Celery fixture

- .github/workflows/test.yaml
- requirements/test-django51.txt
- setup.py
- tox.ini
I've lost track with https://github.com/celery/django-celery-results/pull/458 so re-opening this to add support for newer versions, without dropping anything yet. 
Fix #420
> Add support for Django 5.1 and Python 3.13

- compose.yml
`jazzband` isn't set up as network, but the postgres container uses it, while all other things are using `celery` as network name.
> Use proper network name for postgres container

- django_celery_results/managers.py
- t/integration/benchmark_models.py
- t/unit/test_models.py
> delete expired results in batches to avoid running OOM
